language: java
jdk:
  - oraclejdk8
# Nashorn is only supported in 1.8
#  - oraclejdk7
#  - openjdk7
before_script:
  - cd $TRAVIS_BUILD_DIR/lib
  - wget https://www.dropbox.com/s/6vsztd0u87bm7sd/Spigot.jar
  - cd $TRAVIS_BUILD_DIR
after_success:
  - echo "Nothing to display from files: $TRAVIS_BUILD_DIR/target/*.log"
after_failure:
  - cat $TRAVIS_BUILD_DIR/target/*.log
